{% set name = "py-dom-xpath-six" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b85ac43ae5aba75913517adf871f509c68a8d3fea1586ace92bc44b36cc68cf

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - future
  run:
    - python >={{ python_min }}
    - future

test:
  imports:
    - xpath
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jackjansen/py-dom-xpath-six
  license: MIT
  license_family: MIT
  # license file manually packaged. See https://github.com/jackjansen/py-dom-xpath-six/issues/3
  license_file: LICENSE
  summary: XPath for DOM trees
  description: |
    py-dom-xpath is a pure Python implementation of XPath 1.0. It 
    supports almost all XPath 1.0, with the main exception being the 
    namespace axis. It operates on DOM 2.0 nodes, and works well with 
    xml.dom.minidom.

    py-dom-xpath-redux is a port of py-dom-xpath to enable pypi use.        
    py-dom-xpath-six is a port of py-dom-xpath-redux to Python 3.         
    py-dom-xpath-six requires Python 2.7 or 3.X or greater.

extra:
  recipe-maintainers:
    - ajaypnair09
